---
env:
  browser: true
  es2021: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "airbnb"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: "module"

plugins:
  - react
  - jsx-a11y

rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
      jsx: always
  no-undef: off
  import/no-named-as-default: error
  import/no-named-as-default-member: error
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .js
  func-names: off
  jsx-a11y/heading-has-content: off
  jsx-a11y/label-has-associated-control: off
